name: Bru CLI Tests

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Test local Bru CLI'
        required: true
        default: 'true'

# Assign permissions for unit tests to be reported.
# See https://github.com/dorny/test-reporter/issues/168
permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  test:
    name: CLI Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node Dependencies
        uses: ./.github/actions/common/setup-node-deps

      - name: Display Bru CLI Version
        run: node packages/bruno-cli/bin/bru.js --version

      - name: Run tests
        run: |
          cd packages/bruno-tests/collection
          npm install
          node ../../bruno-cli/bin/bru.js run --env Prod --output junit.xml --format junit --sandbox developer

      - name: Publish Test Report
        uses: dorny/test-reporter@v3
        if: success() || failure()
        with:
          name: Test Report
          path: packages/bruno-tests/collection/junit.xml
          reporter: java-junit
